name: anima_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any

  # Dependencies solved by shared_dependencies module
  provider: any
  get_it: any
  injectable: any
  json_annotation: any
  dio: any
  pretty_dio_logger: any
  meta: any

  # Local Modules
  shared_dependencies:
    path: shared_dependencies

  list:
    path: list

  details:
    path: details

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
